---

- name: Install NTP
  sudo: yes
  apt:
    name: ntp
    state: present
    update_cache: yes
    cache_valid_time: 3600
  notify:
    - stop ntp

- name: Install NTPdate
  sudo: yes
  apt:
    name: ntpdate
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: set Timezone to UTC.
  sudo: yes
  file:
    src: "/usr/share/zoneinfo/UTC"
    dest: "/etc/localtime"
    force: yes
    state: link

- name: Set NTP servers.
  sudo: yes
  command: "ntpdate -q pool.ntp.org"
  notify:
    - start ntp


