---

- name: Create non-root admin user
  hosts: all
  gather_facts: no
  roles:
    - create_user
    - passwordless_sudo
  tags:
    - user

- name: Bootstrap deb based system for further ansible use
  hosts: all
  roles:
    - ansible_deb_bootstrap
  tags:
    - bootstrap

- name: NTP
  hosts: all
  roles:
    - ntp
  tags:
    - ntp

- name: SSH hardening and keyfile setup
  hosts: all
  gather_facts: no
  roles:
    - ssh
  tags:
    - ssh


