---

- name: Harden /etc/ssh/sshd_config
  template: src=sshd_config_template.j2 
            dest=/etc/ssh/sshd_config 
            owner=root
            group=root
            mode=0644
  notify:
    - restart sshd


