---

zsh_user: "{{ new_user | default('admx') }}"
dotfiles_path: "/home/{{ zsh_user }}/dotfiles"
git_clone_targets:
  - repo: "https://github.com/danwakefield/dotfiles.git"
    dest: "{{ dotfiles_path }}"
