---
# vim:ft=ansible:

- name: Ensure apache is not on server.
  apt:
    name: apache2
    state: absent
  notify: stop apache

- name: Install Nginx
  apt:
    name: nginx
    state: present
  notfiy: start nginx
