---

- name: Install zsh
  sudo: yes
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - zsh

- name: Chown dotfiles.
  sudo: yes
  file:
    owner: "{{ zsh_user }}"
    group: "{{ zsh_user }}"
    path: "{{ dotfiles_path }}"
    recurse: yes

- name: Install Stow
  sudo: yes
  apt:
    name: stow
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Unstow dotfiles
  command: "{{ dotfiles_path }}/init.nostow/init.sh"
  args:
    chdir: "{{ dotfiles_path }}/init.nostow/"

- name: Set ZSH as our shell
  sudo: yes
  user:
    name: "{{ zsh_user }}"
    shell: "/bin/zsh"


