---

- name: Install zsh
  sudo: yes
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - zsh

- name: Remove ZSH/custom folder
  file:
    path: "/home/{{ zsh_user }}/.config/ohmyzsh/custom"
    state: absent
    force: yes

- name: Replace custom folder with our our
  file:
    src: "/home/{{ zsh_user }}/dotfiles/zshrc"
    dest: "/home/{{ zsh_user }}/.config/ohmyzsh/custom"
    state: link

- name: Link our zshrc to the right place
  file:
    src: "/home/{{ zsh_user }}/dotfiles/zshrc/zshrc"
    dest: "/home/{{ zsh_user }}/.zshrc"
    state: link
    force: yes

- name: Set ZSH as our shell
  sudo: yes
  user:
    name: "{{ zsh_user }}"
    shell: "/bin/zsh"


