---

- name: Install Git
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - git
    - git-core

- name: Clone repos
  sudo: yes
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    force: yes
  with_items: git_clone_targets
