---

- name: Create user and ensure it belogs to correct groups
  sudo: yes
  user:
    name: "{{ new_user }}"
    password: "{{ new_user_pass }}"
    state: present
    groups: sudo
    append: yes
    shell: "/bin/bash"


