---

domain_name: "danw.eu"
rss_dir_path: "/srv/www/rss/"

git_clone_targets:
  - repo: "https://tt-rss.org/git/tt-rss.git"
    dest: "{{ rss_dir_path }}"

postgresql_ext_install_contrib: yes

postgresql_databases:
  - name: ttrss
    owner: ttrss

postgresql_users:
  - name: ttrss
    pass: ""
    encrypted: no

postgresql_user_priveleges:
  - name: ttrss
    db: ttrss
    priv: "ALL"
