---

- name: Setup new machine
  hosts: all
  roles:
    - {
        role: ansible-deb-bootstrap,
        tags: bootstrap
    }
    - {
        role: create-sudo-user,
        tags: user
    }
    - {
        role: passwordless-sudo,
        tags: ['user', 'sudo']
    }
    - {
        role: ntp,
        tags: ['ntp', 'install']
    }
    - {
        role: fail2ban,
        tags: ['fail2ban', 'install']
    }
    - {
        role: zsh,
        tags: ['zsh', 'install']
    }
    - {
        role: ssh-with-ca,
        tags: ssh
    }
