---

- name: Copy CA SSH key to server.
  sudo: yes
  copy:
    src: ca.pub
    dest: /etc/ssh
    group: root
    owner:  root
    mode: 644

- name: Harden /etc/ssh/sshd_config
  sudo: yes
  template:
    src: sshd_config_template.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify:
    - restart sshd
